"""
Invariants for the shipped signature database (data/signatures/known_hashes.json).

The database is generated by scripts/build_signature_db.py and is committed, while the
corpus it is generated from is not — so these tests validate the shipped artifact itself
and only cross-check against the corpus when it happens to be present.

Two of these guard real failure modes rather than formatting:

  * `test_empty_file_hash_is_absent` — severity is never consulted when deciding
    known-malware status (pipeline.py: `is_known = any(m.match_type == "sha256" ...)`),
    so an entry for the empty file makes a 0-byte upload "known malware" and jumps
    reputation_component from the 0.3 unknown prior to 0.95. De-rating it does not help;
    it has to be absent.

  * `test_no_certificate_is_shared_across_families` — four thumbprints in the corpus are
    shared across unrelated families and all four are Android debug / AOSP test keys. A
    debug key identifies nobody, so shipping one would report every debug-signed APK as
    known malware.
"""
import hashlib
import json
import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.analysis.signatures import normalize_family_name

DB_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "signatures", "known_hashes.json")
MANIFEST = os.path.join(os.path.dirname(__file__), "..", "data", "ttp_apks", "_manifest.json")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
EMPTY_FILE_SHA256 = hashlib.sha256(b"").hexdigest()

# Subject common names that name a build tool, not an actor.
BUILD_TOOL_CNS = {"android debug", "android"}


def _db():
    with open(DB_PATH, encoding="utf-8") as fh:
        return json.load(fh)


def test_database_is_present_and_populated():
    db = _db()
    assert db["hashes"], "signature DB has no hashes — run scripts/build_signature_db.py --apply"
    print(f"OK: {len(db['hashes'])} hashes, {len(db['certificates'])} certificates")


def test_empty_file_hash_is_absent():
    """A 0-byte upload must not match a known signature. See the module docstring."""
    db = _db()
    assert EMPTY_FILE_SHA256 not in db["hashes"], (
        "the empty-file SHA-256 is in the signature DB. Severity cannot suppress this — "
        "is_known_malware keys off match_type alone, so a 0-byte APK would score as known "
        "malware. Remove the entry."
    )


def test_no_fabricated_placeholder_entries():
    """The DB shipped with nine `a1b2c3d4…`-style placeholders. None may come back."""
    db = _db()
    for section in ("hashes", "certificates"):
        for key in db[section]:
            # A real digest does not walk the alphabet in order.
            assert "a1b2c3d4" not in key and "1a2b3c4d" not in key, (
                f"placeholder-looking entry in {section}: {key}"
            )


def test_hash_keys_are_wellformed_sha256():
    db = _db()
    for key in db["hashes"]:
        assert SHA256_RE.match(key), f"not a lowercase hex sha256: {key!r}"


def test_entries_have_complete_metadata():
    db = _db()
    for section, default in (("hashes", 0.9), ("certificates", 0.8)):
        for key, entry in db[section].items():
            for field in ("family", "severity", "source", "description"):
                assert entry.get(field), f"{section}/{key[:12]} missing {field}"
            assert 0.0 <= float(entry["severity"]) <= 1.0, f"{section}/{key[:12]} severity out of range"


def test_families_survive_normalisation_unchanged():
    """
    deterministic_family() normalises whatever the DB holds before it reaches the graph,
    so a name that changes under normalisation would make the DB and the graph disagree
    (e.g. "S.O.V.A." vs "S.O.V.A") and create two MalwareFamily nodes for one family.
    """
    db = _db()
    for section in ("hashes", "certificates"):
        for key, entry in db[section].items():
            raw = entry["family"]
            assert normalize_family_name(raw) == raw, (
                f"{section}/{key[:12]} family {raw!r} normalises to "
                f"{normalize_family_name(raw)!r} — store the normalised form"
            )


def test_no_certificate_is_shared_across_families():
    """A cert used by two families is a build key, not an actor key. See the docstring."""
    db = _db()
    by_family = defaultdict(set)
    for thumb, entry in db["certificates"].items():
        by_family[thumb].add(entry["family"])
    for thumb, fams in by_family.items():
        assert len(fams) == 1, f"certificate {thumb[:12]} claims multiple families: {fams}"


def test_shipped_certificates_are_not_build_tool_keys():
    """
    Cross-check against the corpus when it is present: no shipped thumbprint may belong to
    an APK whose signing certificate is a debug/AOSP test key, and none may appear under
    more than one family in the manifest.
    """
    if not os.path.exists(MANIFEST):
        print("SKIP: corpus not present (data/ttp_apks is gitignored)")
        return

    import warnings
    warnings.filterwarnings("ignore")
    from loguru import logger
    logger.remove()
    from androguard.core.apk import APK
    from app.analysis.ingest import extract_cert_thumbprint
    from app.analysis.apk_static import extract_der_certificates
    from asn1crypto import x509 as ax

    shipped = set(_db()["certificates"])
    manifest = json.load(open(MANIFEST, encoding="utf-8"))["samples"]
    apk_dir = os.path.dirname(MANIFEST)

    seen_families = defaultdict(set)
    for sha, entry in manifest.items():
        path = os.path.join(apk_dir, f"{sha}.apk")
        if not os.path.exists(path):
            continue
        try:
            apk = APK(path)
            thumb = (extract_cert_thumbprint(apk) or "").lower()
        except Exception:
            continue
        if thumb not in shipped:
            continue
        seen_families[thumb].add(entry.get("family"))
        der = extract_der_certificates(apk)
        if der:
            cn = str(ax.Certificate.load(der[0]).subject.native.get("common_name", "")).strip().lower()
            assert cn not in BUILD_TOOL_CNS, (
                f"shipped certificate {thumb[:12]} has build-tool CN {cn!r} — it identifies "
                "a build tool, not an actor, and would flag every debug-signed APK"
            )
    for thumb, fams in seen_families.items():
        assert len(fams) == 1, f"shipped certificate {thumb[:12]} spans families {fams}"
    print(f"OK: {len(seen_families)} shipped certs verified against the corpus")


def test_known_hash_matches_and_unknown_does_not():
    """The security boundary, both directions, against the real shipped DB."""
    from app.core.config import settings
    from app.analysis.signatures import match_signatures, reset_signature_db, deterministic_family

    db = _db()
    known = next(iter(db["hashes"]))
    expected_family = db["hashes"][known]["family"]

    original = settings.online_lookups_enabled
    settings.online_lookups_enabled = False   # local DB only; no network in tests
    reset_signature_db()
    try:
        hit = match_signatures(known, None, DB_PATH)
        assert len(hit) == 1, f"a shipped hash did not match itself: {known[:12]}"
        assert hit[0]["match_type"] == "sha256"
        assert deterministic_family(hit) == expected_family

        miss = match_signatures("f" * 64, None, DB_PATH)
        assert miss == [], f"an unknown hash matched: {miss}"

        empty = match_signatures(EMPTY_FILE_SHA256, None, DB_PATH)
        assert empty == [], "the empty-file hash matched a signature"
    finally:
        settings.online_lookups_enabled = original
        reset_signature_db()
    print("OK: known hash matches, unknown and empty-file do not")
